# Generated by Django 4.2 on 2024-08-20 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sydney_participant', models.CharField(max_length=255)),
                ('sydney_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct_answer_percentage_per_class', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct_answer', models.IntegerField()),
                ('participant', models.CharField(max_length=255)),
                ('student_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category_id', models.IntegerField()),
                ('year_level_name', models.CharField(max_length=255)),
                ('correct_answer_id', models.IntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.answers')),
                ('assessment_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.assessment_areas')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.awards')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
        ),
    ]
