# Generated by Django 4.2 on 2024-08-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarystudent',
            name='student_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='summarystudent',
            name='school',
            field=models.CharField(max_length=255),
        ),
    ]
