# Generated by Django 4.2 on 2024-08-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_summarystudent_student_id_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarystudent',
            name='student_name',
            field=models.CharField(default=models.IntegerField(default='1'), max_length=255),
        ),
    ]
